22 modif evento
Culturale/culturale-server pull request #18
Opened 2023-03-30 21:26 UTC by martareluy

# Description
**No pasa el test, pero no se hacerlo, se aceptan sugerencias :)** Todo lo demás hecho, tambien el merge con la última version de main para que no de problemas :p 
## Context

(Optional)

Current situation of the system, explanation why this PR is needed.

## Goal

Explanation about what we want to achieve with this PR.

## Support documents

- Taiga Ticket: [ticket](link)

- UI/UX design: [link](https://paack.co)

## Design considerations

(Optional)

Section dedicated to explain what design considerations we had while coding this PR.

# Testing

Section dedicated to explain how and what to test in this PR.

# Configuration

## New environment

(Optional)

Environment variables added/changed that needs to be added manually by the other developers

## New dependencies

(Optional)

New packages/libraries added / updated

# Attachments

(Optional)

- <details closed>
    <img src="https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" width="50%" height="50%">
  </details>

Section dedicated to add any screenshots or other documents we find relevant to help understand or analyze this PR.

# Dependencies or blockers

(Optional: List of dependencies or blockers that make this PR not yet ready to be merged with the main branch)
## Subtasks

(List of subtask PRs needed for this feature)

- [ ] #XX
...

2023-03-30 21:57 UTC, quimvi requested changes

2023-03-30 21:57 UTC, quimvi commented on src/infrastructure/dtos/edit-event.dto.ts
> +export class EditParamDTO {
Millor dir-li editEventDTO

2023-03-30 21:57 UTC, quimvi commented on src/application/controllers/event-controller/event-controller.ts
> +  public static async editEvent(req: Request, res: Response): Promise<void> {
Crec que aqui faria falta veure que passa si no troba l'event que es vol modificar

2023-03-30 21:57 UTC, quimvi commented on src/infrastructure/api/event-router/event-router.test.ts
> +      //expect(res.updatedEvent.descripcio).toBe('new-test-description');
Borra els comments

2023-03-30 21:57 UTC, quimvi commented on src/infrastructure/api/event-router/event-router.test.ts
> +      expect(res.body.success).toBe(false);
El codi et peta perk no te un camp de success al body si el payload es incorrecte.
Hauries de comprobar que el camp de errors te coses. per exemple:
```suggestion
      expect(res.body.errors).toBeTruthy()
```

2023-03-30 21:57 UTC, quimvi commented on src/infrastructure/dtos/edit-event.dto.ts
> +    denominacio: string | null;
Si es optional no cal posar `string | null`. Si poses que es optional ja dius que pot ser  null

2023-03-30 21:57 UTC, quimvi commented on src/application/controllers/event-controller/event-controller.ts
> +  public static async editEvent(req: Request, res: Response): Promise<void> {
Si fas aixo tambe posa un test mes per intentar modificar un event que no existeix

2023-04-04 11:13 UTC, quimvinals approved these changes

2023-04-04 11:15 UTC, quimvi approved these changes

2023-04-07 16:57 UTC, merged