Cambio de algunos parametros a opcionales
Culturale/culturale-server pull request #39
Opened 2023-05-12 01:31 UTC by Titustitus00

# Description

## Context

(Optional)

Current situation of the system, explanation why this PR is needed.

## Goal

Explanation about what we want to achieve with this PR.

## Support documents

- Taiga Ticket: [ticket](link)

- UI/UX design: [link](https://paack.co)

## Design considerations

(Optional)

Section dedicated to explain what design considerations we had while coding this PR.

# Testing

Section dedicated to explain how and what to test in this PR.

# Configuration

## New environment

(Optional)

Environment variables added/changed that needs to be added manually by the other developers

## New dependencies

(Optional)

New packages/libraries added / updated

# Attachments

(Optional)

- <details closed>
    <img src="https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" width="50%" height="50%">
  </details>

Section dedicated to add any screenshots or other documents we find relevant to help understand or analyze this PR.

# Dependencies or blockers

(Optional: List of dependencies or blockers that make this PR not yet ready to be merged with the main branch)
## Subtasks

(List of subtask PRs needed for this feature)

- [ ] #XX
...

2023-05-14 10:49 UTC, quimvi requested changes

2023-05-14 10:49 UTC, quimvi commented on src/domain/entities/event/event.schema.ts
> +  url: { required: false, type: String },
Hay que updatear tmb el shcema, la interface y la entity para updatear los cambios acorde a esto. Para hacer los campos que tocan opcionales

2023-05-22 07:04 UTC, quimvinals commented on src/infrastructure/dtos/create-event.dto.ts
> +  @IsOptional()
Lat i Long no deberian ser obligatorios?

2023-05-22 14:15 UTC, Titustitus00 commented on src/infrastructure/dtos/create-event.dto.ts
> +  @IsOptional()
esos parametros ya eran opcionales antes de que yo modificase los parametros
todos los eventos que obtengo de la generalitat en el script han de tener lat y long obligatoriamente y entonces cambié unos pocos parametros a opcionales para poder obtener los eventos de la generalitat

Quieres que ponga a obligatorios todos los parametros que necesito en el script?

2023-05-28 16:06 UTC, quimvi approved these changes

2023-05-28 16:06 UTC, merged