Edit password
Culturale/culturale-server pull request #40
Opened 2023-05-14 02:37 UTC by Titustitus00

# Description

## Context

(Optional)

Current situation of the system, explanation why this PR is needed.

## Goal

Explanation about what we want to achieve with this PR.

## Support documents

- Taiga Ticket: [ticket](link)

- UI/UX design: [link](https://paack.co)

## Design considerations

(Optional)

Section dedicated to explain what design considerations we had while coding this PR.

# Testing

Section dedicated to explain how and what to test in this PR.

# Configuration

## New environment

(Optional)

Environment variables added/changed that needs to be added manually by the other developers

## New dependencies

(Optional)

New packages/libraries added / updated

# Attachments

(Optional)

- <details closed>
    <img src="https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" width="50%" height="50%">
  </details>

Section dedicated to add any screenshots or other documents we find relevant to help understand or analyze this PR.

# Dependencies or blockers

(Optional: List of dependencies or blockers that make this PR not yet ready to be merged with the main branch)
## Subtasks

(List of subtask PRs needed for this feature)

- [ ] #XX
...

2023-05-14 10:52 UTC, quimvi requested changes

2023-05-14 10:52 UTC, quimvi commented on src/infrastructure/api/user-router/user-routes.ts
> +userRouter.patch('/users/id/:id/edit/changePassword', changePasswordDto, UserController.changePassword);
```suggestion
userRouter.patch('/users/:id/changePassword', changePasswordDto, UserController.changePassword);
```

2023-05-14 10:52 UTC, quimvi commented on src/application/controllers/user-controller/user-controller.ts
> +      const new_password: string = req.body.new_password;
Hay que crear un objeto de tipo ChangePasswordDTO e igualrlo al body de la request

2023-05-18 16:12 UTC, quimvinals approved these changes

2023-05-18 16:15 UTC, quimvi approved these changes

2023-05-18 16:16 UTC, merged